server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: spring-boot-best-practices

  datasource:
    url: jdbc:postgresql://localhost:5432/spring_boot_best_practices
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
